import { DarkTheme } from '@react-navigation/native';
import { StyleSheet } from 'react-native';

export const colors = {
  background: '#050505',
  surface: '#101010',
  surfaceMuted: '#181818',
  surfaceSoft: '#1f1f1f',
  border: '#282828',
  text: '#f5f5f5',
  textMuted: '#9b9b9b',
  accent: '#e11d2f',
  accentSoft: '#4a1116',
  white: '#ffffff',
};

export const navigationTheme = {
  ...DarkTheme,
  colors: {
    ...DarkTheme.colors,
    primary: colors.accent,
    background: colors.background,
    card: colors.surface,
    text: colors.text,
    border: colors.border,
    notification: colors.accent,
  },
};

export const appStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 12,
  },
  authContent: {
    flexGrow: 1,
    padding: 24,
    justifyContent: 'center',
  },
  brandBadge: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  brandBadgeText: {
    color: colors.white,
    fontSize: 34,
    fontWeight: '800',
  },
  eyebrow: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  authTitle: {
    color: colors.text,
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '800',
    marginBottom: 12,
  },
  authSubtitle: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 24,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 16,
  },
  inputGroup: {
    gap: 8,
    width: '100%',
  },
  inputLabel: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  input: {
    backgroundColor: colors.surfaceSoft,
    color: colors.text,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
  },
  inputError: {
    borderColor: colors.accent,
  },
  inputErrorText: {
    color: '#ff8f98',
    fontSize: 13,
    fontWeight: '600',
  },
  formStatus: {
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
  },
  formStatusSuccess: {
    backgroundColor: '#10281a',
    borderColor: '#1f7a43',
  },
  formStatusInfo: {
    backgroundColor: '#122031',
    borderColor: '#315a88',
  },
  formStatusError: {
    backgroundColor: '#341317',
    borderColor: colors.accent,
  },
  formStatusText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  primaryButton: {
    backgroundColor: colors.accent,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    width: '100%',
  },
  primaryButtonPressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.92,
  },
  primaryButtonDisabled: {
    opacity: 0.88,
  },
  primaryButtonLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '800',
  },
  secondaryButton: {
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    width: '100%',
  },
  secondaryButtonText: {
    color: colors.text,
    fontWeight: '700',
  },
  pageContent: {
    padding: 20,
    paddingBottom: 120,
    gap: 18,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  inlineHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  pageTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
  },
  softButton: {
    backgroundColor: '#273043',
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderRadius: 12,
  },
  softButtonText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '500',
  },
  scanButton: {
    backgroundColor: colors.accent,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 12,
  },
  scanButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '800',
  },
  heroCard: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 20,
  },
  heroTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 8,
  },
  heroSubtitle: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 24,
  },
  sectionBlock: {
    gap: 10,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  sectionMeta: {
    color: colors.textMuted,
    fontSize: 14,
  },
  homeFeatureImage: {
    width: '100%',
    height: 220,
    borderRadius: 20,
    backgroundColor: colors.surface,
  },
  channelCard: {
    height: 250,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    marginBottom: 16,
  },
  channelImage: {
    width: '100%',
    height: '100%',
  },
  channelOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.42)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  channelTitle: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '800',
  },
  channelMeta: {
    color: '#d1d1d1',
    fontSize: 16,
  },
  channelListCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    gap: 14,
  },
  channelListPressable: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  channelListIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  channelListBody: {
    flex: 1,
    gap: 4,
  },
  channelListTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '800',
  },
  channelListMeta: {
    color: colors.textMuted,
    fontSize: 13,
  },
  channelDeleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    width: '100%',
    backgroundColor: colors.accentSoft,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.accent,
    paddingVertical: 12,
  },
  channelDeleteButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '800',
  },
  directoryReviewCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    gap: 14,
  },
  directoryReviewRow: {
    gap: 6,
  },
  directoryReviewLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  directoryReviewValue: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  directoryReviewPath: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 22,
  },
  directoryReviewActions: {
    gap: 12,
  },
  directoryProgressFile: {
    color: colors.textMuted,
    fontSize: 13,
    marginTop: 8,
  },
  emptyState: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 24,
    alignItems: 'center',
    gap: 8,
  },
  emptyStateTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
  },
  emptyStateText: {
    color: colors.textMuted,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
  },
  reelSlide: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.background,
    justifyContent: 'flex-end',
  },
  reelImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  reelVideo: {
    ...StyleSheet.absoluteFillObject,
  },
  reelTapSurface: {
    ...StyleSheet.absoluteFillObject,
  },
  reelOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  reelActions: {
    position: 'absolute',
    right: 16,
    bottom: 120,
    gap: 22,
    alignItems: 'center',
  },
  actionGroup: {
    alignItems: 'center',
    gap: 8,
  },
  actionCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: 'rgba(10,10,10,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionLabel: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  reelCaption: {
    padding: 20,
    backgroundColor: 'rgba(0,0,0,0.28)',
  },
  reelCreator: {
    color: colors.accent,
    fontWeight: '700',
    marginBottom: 8,
  },
  reelTitle: {
    color: colors.white,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '800',
    maxWidth: '82%',
    marginBottom: 8,
  },
  reelMeta: {
    color: '#d1d1d1',
    fontSize: 14,
  },
  reelDurationBadge: {
    position: 'absolute',
    top: 62,
    left: 16,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  reelDurationText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '700',
  },
  reelPlaybackBadge: {
    position: 'absolute',
    top: 62,
    right: 16,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  reelPlaybackBadgeText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '800',
  },
  reelSpeedBadge: {
    position: 'absolute',
    top: 110,
    right: 16,
    backgroundColor: colors.accent,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  reelSpeedBadgeText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '800',
  },
  uploadPanel: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 24,
    alignItems: 'stretch',
    gap: 14,
  },
  uploadTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 32,
  },
  uploadSubtitle: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 24,
  },
  uploadPreviewCard: {
    width: '100%',
    gap: 10,
  },
  uploadPreviewImage: {
    width: '100%',
    height: 220,
    borderRadius: 18,
    backgroundColor: colors.surfaceMuted,
  },
  uploadPreviewPlaceholder: {
    width: '100%',
    height: 220,
    borderRadius: 18,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadPreviewLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  uploadPreviewMeta: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  textArea: {
    minHeight: 120,
    paddingTop: 14,
  },
  profileHeader: {
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  avatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.accent,
  },
  avatarText: {
    color: colors.white,
    fontSize: 32,
    fontWeight: '800',
  },
  profileName: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '800',
  },
  profileHandle: {
    color: colors.textMuted,
    fontSize: 15,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
  },
  statValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
  },
  statLabel: {
    color: colors.textMuted,
    marginTop: 4,
  },
  cardRow: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  cardRowText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  searchInput: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 18,
    paddingVertical: 16,
    color: colors.text,
    fontSize: 16,
  },
  toggleRow: {
    flexDirection: 'row',
    gap: 10,
  },
  toggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  toggleButtonActive: {
    backgroundColor: colors.accent,
    borderColor: '#ff5a67',
  },
  toggleButtonText: {
    color: colors.text,
    fontWeight: '700',
  },
  searchResultsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 14,
  },
  searchResultsList: {
    gap: 14,
  },
  videoCardGrid: {
    width: '48%',
    backgroundColor: colors.surface,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
  },
  videoCardList: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
  },
  videoCardHome: {
    backgroundColor: colors.background,
    marginBottom: 20,
  },
  videoCardGridImageWrap: {
    position: 'relative',
  },
  videoCardHomeImageWrap: {
    position: 'relative',
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  videoCardGridImage: {
    width: '100%',
    height: 170,
  },
  videoCardHomeImage: {
    width: '100%',
    height: 220,
  },
  videoCardPlaceholderGrid: {
    width: '100%',
    height: 170,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCardPlaceholderHome: {
    width: '100%',
    height: 220,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCardListImageWrap: {
    width: 150,
    position: 'relative',
  },
  videoCardListImage: {
    width: '100%',
    height: '100%',
    minHeight: 110,
  },
  videoCardPlaceholderList: {
    width: '100%',
    minHeight: 110,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCardPlaceholderText: {
    color: colors.textMuted,
    fontWeight: '700',
  },
  videoCardDuration: {
    position: 'absolute',
    right: 10,
    bottom: 10,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  videoCardDurationText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '700',
  },
  videoCardGridBody: {
    padding: 14,
    gap: 6,
  },
  videoCardListBody: {
    flex: 1,
    padding: 14,
    gap: 6,
    justifyContent: 'center',
  },
  videoCardHomeBody: {
    paddingTop: 12,
  },
  videoCardHomeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  videoCardHomeAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCardHomeAvatarText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '800',
  },
  videoCardHomeTitleWrap: {
    flex: 1,
    gap: 4,
    paddingRight: 8,
  },
  videoCardHomeTitle: {
    color: colors.text,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
  },
  videoCardTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '700',
  },
  videoCardMeta: {
    color: colors.textMuted,
    fontSize: 13,
  },
  videoHero: {
    width: '100%',
    height: 240,
    backgroundColor: colors.surface,
  },
  videoPageBody: {
    padding: 18,
    paddingBottom: 120,
    gap: 18,
  },
  videoPageTitle: {
    color: colors.text,
    fontSize: 22,
    lineHeight: 30,
    fontWeight: '800',
  },
  videoPageMeta: {
    color: colors.textMuted,
    fontSize: 14,
  },
  videoActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  videoActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  videoActionButtonActive: {
    backgroundColor: colors.accent,
    borderColor: '#ff5a67',
  },
  videoActionText: {
    color: colors.text,
    fontWeight: '700',
  },
  videoChannelCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
  },
  videoChannelAvatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
  },
  videoChannelAvatarPlaceholder: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoChannelAvatarPlaceholderText: {
    color: colors.white,
    fontWeight: '800',
  },
  videoChannelMetaWrap: {
    flex: 1,
    gap: 4,
  },
  videoChannelName: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  videoChannelSubscribers: {
    color: colors.textMuted,
    fontSize: 13,
  },
  videoSubscribeButton: {
    backgroundColor: colors.accent,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  videoSubscribeText: {
    color: colors.white,
    fontWeight: '800',
  },
  videoDescriptionCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    gap: 10,
  },
  videoDescriptionHeading: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  videoDescriptionText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  savedCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    gap: 10,
  },
  savedType: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  savedTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
  },
  tabBar: {
    backgroundColor: '#050505',
    borderTopColor: colors.border,
    height: 84,
    paddingTop: 10,
    paddingBottom: 10,
  },
  tabLabel: {
    fontSize: 12,
    fontWeight: '600',
  },
  uploadTabButton: {
    width: 66,
    height: 66,
    borderRadius: 33,
    marginBottom: 28,
    backgroundColor: '#20283a',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2c3550',
  },
  uploadTabButtonActive: {
    backgroundColor: colors.accent,
    borderColor: '#ff5a67',
  },
});
